package com.mitti.entrepreneur.constants;

public interface Constant {

    int MAXIMUM_DEGREE = 360;

    double GLOBAL_FACTOR_WEIGHT = 1.1;
    double DOMESTIC_FACTOR_WEIGHT = 1.2;
    double CENTRAL_BANK_INTEREST_WEIGHT = 1.3;
    double CURRENCY_DEPRECIATION_WEIGHT = 1.4;

    double ENGINEER_COST = 200;
    double EXECUTIVE_COST = 150;
    double REPUTATION_FACTOR_ON_HIRE = 0.1;
    double REPUTATION_FACTOR_ON_LAYOFF = 0.25;
    double REPUTATION_FACTOR_ON_LOAN = 0.01;

    double REVENUE_FACTOR_ON_PRODUCT_ADDITION = 50.5;
    double REPUTATION_FACTOR_ON_PRODUCT_ADDITION = 1.5;

    int COUNT_OF_MARKET_FACTORS = 4;
    int PRODUCT_COST_PERCENTAGE_PER_RESOURCE = 50;

    int GLOBAL_FACTOR_CHANGE_DEGREE = 28;
    int DOMESTIC_FACTOR_CHANGE_DEGREE = 35;
    int CENTRAL_BANK_INTEREST_FLUCTUATION = 20;
    int CURRENCY_FLUCTUATION_DEGREE = 15;
}
